services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: votary_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    container_name: votary_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votary_db
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
volumes:
  mysql-data:
