services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: votary_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
      - whisper_cache:/root/.cache/whisper
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - votary_network
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: "2.0"

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    container_name: votary_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votary_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - votary_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - votary_network

networks:
  votary_network:
    driver: bridge

volumes:
  mysql-data:
  whisper_cache:
